services:
  postgres-asap:
    image: 'postgis/postgis:latest'
    container_name: postgres-asap
    platform: linux/amd64
    environment:
      - 'POSTGRES_DB=asap'
      - 'POSTGRES_PASSWORD=asap'
      - 'POSTGRES_USER=asap'
    ports:
      - '5432:5432'

  minio-asap:
    image: minio/minio:latest
    container_name: minio-asap
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: asap-local
      MINIO_ROOT_PASSWORD: asap-local
    entrypoint: >
      /bin/sh -c "
        mkdir -p /data/asap &&
        exec minio server /data --console-address :9001
      "
